# Generated by Django 2.1 on 2020-07-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersReg',
            new_name='blogForm',
        ),
    ]
